// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CityLinkage: typeof import('./src/components/city-linkage/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FormDialog: typeof import('./src/components/form-dialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
